Update git actions

diff --git a/.github/workflows/liblab-generate-sdks.yaml b/.github/workflows/liblab-generate-sdks.yaml
--- a/.github/workflows/liblab-generate-sdks.yaml
+++ b/.github/workflows/liblab-generate-sdks.yaml
@@ -1,25 +1,41 @@
 name: Generate SDKs using liblab
 
 on:
-  # Add any other triggers you want here, such as a push to the spec file
   workflow_call:
   workflow_dispatch:
-
+  push:
+    branches:
+      - main
+    paths:
+      - 'liblab.config.json'
+      - 'spec.json'
+      - 'hooks/**'
+      - 'customPlanModifiers/**'
 jobs:
   build-and-pr:
     name: Generate SDKs and create PRs
     runs-on: ubuntu-latest
+    if: github.run_number != 1
     env:
+      LIBLAB_CI: true
       LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
       GITHUB_TOKEN: ${{ secrets.LIBLAB_GITHUB_TOKEN }}
-      LIBLAB_ENVIRONMENT: development
     steps:
+      - name: Check if secrets are set
+        run: |
+          if [[ -n "${{ secrets.LIBLAB_TOKEN }}" && -n "${{ secrets.LIBLAB_GITHUB_TOKEN }}" ]]; then
+            echo "Secrets are set, proceeding with the workflow"
+          else
+            echo "Error: Secrets LIBLAB_TOKEN and LIBLAB_GITHUB_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-github-actions/#create-tokens"
+            echo "::error::Secrets LIBLAB_TOKEN and LIBLAB_GITHUB_TOKEN are required, see https://developers.liblab.com/tutorials/integrate-with-github-actions/#create-tokens"
+            exit 1
+          fi
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Node.js environment
         uses: actions/setup-node@v4
         with:
-          node-version: "20" # Specify the node version you want to use
+          node-version: '20'
       - name: Install liblab
         run: npm install -g liblab
       - name: Start Build
